name: Pull Request checks
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests
        run: go test ./... -v -coverprofile=profile.cov
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
      - uses: codecov/codecov-action@v5
        with:
          files: profile.cov

      - name: Run go vet
        run: go vet ./...
